language: php

dist: precise

branches:
  only:
    - dev
    - master
php:
  - 5.6
  - 7.0

sudo: false

install:
  - composer install

script:
  - php ./vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
